export const templates = [
  {
    id: 'basic',
    name: 'Basic',
    className: 'p-4',
    headerClass: '',
    qrWrapperClass: '',
    footerClass: '',
  },
  {
    id: 'text-below',
    name: 'Text Below',
    className: 'p-4 flex flex-col items-center gap-2',
    headerClass: '',
    qrWrapperClass: '',
    footerClass: 'text-sm font-medium',
  },
  {
    id: 'header',
    name: 'Header',
    className: 'rounded-lg overflow-hidden',
    headerClass: 'bg-[var(--qr-accent-color)] p-2 text-center text-sm font-medium',
    qrWrapperClass: 'p-4',
    footerClass: 'text-sm text-center py-2',
  },
  {
    id: 'side-bars',
    name: 'Side Bars',
    className: 'p-4 relative',
    headerClass: '',
    qrWrapperClass: 'relative z-10',
    footerClass: 'text-sm text-center mt-2',
    beforeClass: 'before:absolute before:left-0 before:top-1/2 before:-translate-y-1/2 before:w-16 before:h-32 before:bg-[var(--qr-accent-color)] before:rounded-r-lg before:-z-0',
    afterClass: 'after:absolute after:right-0 after:top-1/2 after:-translate-y-1/2 after:w-16 after:h-32 after:bg-[var(--qr-accent-color)] after:rounded-l-lg after:-z-0',
  },
  {
    id: 'curved',
    name: 'Curved',
    className: 'p-4 relative',
    headerClass: '',
    qrWrapperClass: 'relative z-10',
    footerClass: 'text-sm text-center mt-2',
    beforeClass: 'before:absolute before:inset-0 before:bg-[var(--qr-accent-color)] before:rounded-[30%] before:-z-0',
  },
  {
    id: 'gradient',
    name: 'Gradient',
    className: 'p-4 relative',
    headerClass: '',
    qrWrapperClass: 'relative z-10',
    footerClass: 'text-sm text-center mt-2',
    beforeClass: 'before:absolute before:inset-0 before:bg-gradient-to-b before:from-[var(--qr-accent-color)] before:to-transparent before:-z-0',
  },
  {
    id: 'frame',
    name: 'Frame',
    className: 'p-1',
    headerClass: '',
    qrWrapperClass: 'border-4 border-[var(--qr-accent-color)] rounded-lg p-4',
    footerClass: 'text-sm text-center mt-2',
  },
]

