export const templates = [
  {
    id: "minimal",
    name: "Minimal",
    className: "p-4",
    headerClass: "",
    qrWrapperClass: "",
    footerClass: "",
  },
  {
    id: "rounded",
    name: "Rounded corners",
    className: "p-4 flex flex-col items-center gap-2",
    headerClass: "",
    qrWrapperClass: "",
    footerClass: "text-sm font-medium text-center",
  },
  {
    id: "banner",
    name: "Banner top",
    className: "overflow-hidden rounded-xl",
    headerClass: "bg-(--qr-accent-color) p-3 text-center text-xs font-semibold uppercase tracking-wide",
    qrWrapperClass: "p-4",
    footerClass: "pb-3 text-xs text-center font-medium",
  },
  {
    id: "pocket",
    name: "Pocket",
    className: "relative overflow-hidden rounded-lg p-4",
    headerClass: "",
    qrWrapperClass: "relative z-10",
    footerClass: "mt-2 text-xs text-center uppercase tracking-wide",
    beforeClass: "before:absolute before:left-0 before:top-1/2 before:h-24 before:w-16 before:-translate-y-1/2 before:rounded-r-2xl before:bg-[var(--qr-accent-color)] before:-z-0",
    afterClass: "after:absolute after:right-0 after:top-1/2 after:h-24 after:w-16 after:-translate-y-1/2 after:rounded-l-2xl after:bg-[var(--qr-accent-color)] after:-z-0",
  },
  {
    id: "wave",
    name: "Wave",
    className: "relative overflow-hidden rounded-lg p-4",
    headerClass: "",
    qrWrapperClass: "relative z-10",
    footerClass: "mt-2 text-xs text-center uppercase tracking-wide",
    beforeClass: "before:absolute before:inset-0 before:-z-0 before:rounded-[30%] before:bg-[var(--qr-accent-color)] before:opacity-60",
  },
  {
    id: "arc",
    name: "Arc highlight",
    className: "relative overflow-hidden rounded-lg p-4",
    headerClass: "",
    qrWrapperClass: "relative z-10",
    footerClass: "mt-2 text-xs text-center uppercase tracking-wide",
    beforeClass: "before:absolute before:inset-x-0 before:top-0 before:h-1/2 before:bg-gradient-to-b before:from-[var(--qr-accent-color)] before:to-transparent before:-z-0",
  },
  {
    id: "frame",
    name: "Border frame",
    className: "p-2",
    headerClass: "",
    qrWrapperClass: "rounded-xl border-4 border-[var(--qr-accent-color)] p-4",
    footerClass: "mt-2 text-xs text-center uppercase tracking-wide",
  },
] as const
